version: "2.6"

services:
  sngnn2d-v2:
    runtime: nvidia
    container_name: sngnn2d-v2
    image: nvcr.io/nvidia/dgl:23.11-py3
    ipc: host
    stdin_open: true
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./:/workspace

